//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterClashServer.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int IDPartida { get; set; }
        public int IDAnfitrion { get; set; }
        public Nullable<int> IDAdivinador { get; set; }
        public int IDPalabra { get; set; }
        public string Estado { get; set; }
        public string Resultado { get; set; }
        public string Privacidad { get; set; }
        public int Turno { get; set; }
        public string CodigoAcceso { get; set; }
        public System.DateTime FechaDeJuego { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Jugador Jugador1 { get; set; }
        public virtual Palabra Palabra { get; set; }
    }
}
